config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  get '/messages' => 'conversations#index'
  get '/index' => 'home#index'
  get '/notifications' => 'pages#profile'
  get '/explore' => 'pages#explore'
  get '/search' => 'pages#search', as:'search'
  get 'search_results' => 'pages#search_results', as: 'search_results'
  get 'hashtags/',         to: 'hashtags#index',     as: :hashtags
  get 'hashtags/:hashtag', to: 'hashtags#show',      as: :hashtag

  authenticated :user do
    root to: "home#index", as: "home"
  end
  unauthenticated :user do
    root 'static_pages#index'
  end

  resources :tweets, except: [:new, :edit] do
    member do
      post :reply
    end
  end

resources :tweets do 
  member do
    put "like", to: "tweets#like"
  end
end

  resources :users, except: [:new, :create] do
    member do
      get 'followers'
      get 'following'
      get 'favorites'
      get 'retweets'
      get 'likes'
    end
  end 

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  resources :find_friends, only: :index
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
  resources :comments
  
  member do
    post :reply
  end
 end
  

end 

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  
  self.per_page = 20
  
  belongs_to :user
  belongs_to :parent, class_name: "Tweet"
  has_many :replies, class_name: "Tweet", foreign_key: "parent_id"
  has_many :favorites
  has_many :likes
  has_many :friends
  has_many :retweets, foreign_key: "source_tweet_id"
  validates :tweet_text, presence: true, length: { maximum: 140 }

  counter_culture :user

  mount_uploader :media, MediaUploader
  mount_uploader :video, VideoUploader
  
  acts_as_votable
  
  acts_as_punchable
  
  def self.search(search)
  where("tweet_text LIKE ?", "%#{search}%")
  end
  
  def self.popularity(popularity)
  order("COALESCE(likes, ?) DESC").limit(5)
  end
  
  include SimpleHashtag::Hashtaggable
  hashtaggable_attribute :tweet_text
  
  include PublicActivity::Model
  tracked
  
end 
  
  

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!
 
  def create
    @tweet = Tweet.new(tweet_params) do |tweet|
      tweet.user = current_user
      tweet.parent_id = params[:parent_id]
      @activities = PublicActivity::Activity.order("created_at desc")
    end 
    respond_to do |format|
      format.js
    end
  end

  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    @activities = PublicActivity::Activity.order("created_at desc")
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet_id = params[:id]
    respond_to do |format|
      format.js
    end
  end

  def reply
    @tweet = Tweet.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
  
  
  def like 
  @tweet = Tweet.find(params[:id])
  @tweet.like_by current_user
  redirect_to :back
  end  
  
  private
  def tweet_params
    params.require(:tweet).permit(:tweet_text, :location, :media, :video, :tag_list)
  end
  
end 

app/helpers/tweets_helper.rb
module TweetsHelper
  def get_favorite(tweet_id)
    current_user.favorites.find_by(tweet_id: tweet_id)
  end

  def tweet_favored?(tweet_id)
    !get_favorite(tweet_id).nil?
  end

  def get_retweet(tweet_id)
    current_user.retweets.find_by(source_tweet_id: tweet_id)
  end

  def retweeted?(tweet_id)
    !get_retweet(tweet_id).nil?
  end

  def can_retweet?(tweet_id)
    Tweet.find(tweet_id).user != current_user
  end
  
   def get_like(tweet_id)
    current_user.likes.find_by(tweet_id: tweet_id)
   end

  def tweet_liked?(tweet_id)
    !get_like(tweet_id).nil?
  end
  
end

app/views/tweets/_tweet.html.erb
<div id="tweet-<%= tweet.id %>" class="micropost">
  <div class="content">
    <div class="avatar-content">
      <%= link_to tweet.user do %>
        <%= render 'partials/avatar', user: tweet.user, klass: 'avatar' %>
      <% end %>
    </div>
    <div class="post-content">
      <%= link_to tweet.user do %>
        <span class="name"><%= tweet.user.name %></span>
      <% end %>
      <%= link_to tweet.user do %>
        <span class="username">@<%= tweet.user.username %></span>
      <% end %>
      <div class="post">
        <%= auto_link(parse(tweet.tweet_text), html: { target: '_blank' }) %>
      </div>
      <div class="media">
        <%= image_tag tweet.media_url, style: "width: 100%; margin-top: 10px;" if tweet.media? %>
        <%= video_tag tweet.media_url, :controls =>true if tweet.media? %>
      </div>
    </div>
    <div class="right-content">
      <span><%= relative_time(tweet.created_at) %></span>
    </div>
  </div>
  <div class="actions">
    <div class="actions-content">
      <%= link_to reply_tweet_path(tweet.id), method: :post, remote: true do %>
        <i class="glyphicon glyphicon-comment"></i>
      <% end %>
        <span id="favor-tweet-<%= tweet.id %>">
          <%= tweet.favorites.size %>
        <%= render 'favorites/favorite_button', tweet_id: tweet.id %>
      </span>
     <%= link_to like_tweet_path(tweet), method: :put do %>
         <i class="glyphicon glyphicon-fire"></i>
         <%= tweet.get_likes.size %>
      <% end %>
      <% if tweet.user == current_user %>
        <%= link_to tweet_path(tweet), method: :delete, remote: true do %>
          <i class="fa fa-trash"></i>
        <% end %>
        <% end %>
    </div>
  </div>
  <div class="reply-form">
  </div>
</div>

app/views/tweets/create.js.erb
<% if @tweet.save %>
  $("#tweet_tweet_text").val("");
  $("#feed").prepend("<%=j render @tweet %>");
 	$('#tweet-error').html("<%=j render 'partials/error_message', error_message: 'Tweet posted successfully to your timeline' %>");
  $('#tweet-count').text('140');
 	$("#new-tweet-modal").modal('hide');
 	$('#tweets-count').html("<%= current_user.reload.tweets_count %>");
<% else %>
	$('#tweet-error').html("<%=j render 'partials/error_message', error_message: @tweet.errors.full_messages.first %>");
<% end %>

app/views/tweets/destroy.js.erb
<% if @tweet.destroy %>
  $("#tweet-<%= @tweet_id %>").remove();
  $('#tweets-count').html("<%= current_user.reload.tweets_count %>");
  $('#tweet-error').html("<%=j render 'partials/error_message', error_message: 'Tweet deleted successfully' %>");
<% else %>
  $('#tweet-error').html("<%=j render 'partials/error_message', error_message: 'Tweet deletion failed. Try again later' %>");
<% end %>

app/views/tweets/reply.js.erb
$("#tweet-<%= @tweet.id %> .reply-form").html("<%=j render 'partials/reply_tweet', tweet: @tweet %>");