config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  get '/messages' => 'conversations#index'
  get '/index' => 'home#index'
  get '/notifications' => 'pages#profile'
  get '/explore' => 'pages#explore'
  get '/search' => 'pages#search', as:'search'
  get 'search_results' => 'pages#search_results', as: 'search_results'
  get 'hashtags/',         to: 'hashtags#index',     as: :hashtags
  get 'hashtags/:hashtag', to: 'hashtags#show',      as: :hashtag

  authenticated :user do
    root to: "home#index", as: "home"
  end
  unauthenticated :user do
    root 'static_pages#index'
  end

  resources :tweets, except: [:new, :edit] do
    member do
      post :reply
    end
  end

resources :tweets do 
  member do
    put "like", to: "tweets#like"
  end
end

  resources :users, except: [:new, :create] do
    member do
      get 'followers'
      get 'following'
      get 'favorites'
      get 'retweets'
      get 'likes'
    end
  end 

  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :retweets, only: [:create, :destroy]
  resources :find_friends, only: :index
  resources :messages, only: [:new, :create]
  resources :conversations, only: [:index, :show, :destroy] do
  resources :comments
  
  member do
    post :reply
  end
 end
  

end 

app/models/click.rb
class Click < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :tweet
  belongs_to :user
  acts_as_votable
  include PublicActivity::Model
  tracked
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/likes.rb
class Likes < ActiveRecord::Base
belongs_to :tweet
belongs_to :user
include PublicActivity::Model
tracked
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
  counter_culture :user, column_name: :following_count
  counter_culture :friend, column_name: :followers_count
end

app/models/retweet.rb
class Retweet < ActiveRecord::Base
  belongs_to :retweeter, class_name: "User"
  belongs_to :source_tweet, class_name: "Tweet"

  validates_presence_of :retweeter

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  
  self.per_page = 20
  
  belongs_to :user
  belongs_to :parent, class_name: "Tweet"
  has_many :replies, class_name: "Tweet", foreign_key: "parent_id"
  has_many :favorites
  has_many :likes
  has_many :friends
  has_many :retweets, foreign_key: "source_tweet_id"
  validates :tweet_text, presence: true, length: { maximum: 140 }

  counter_culture :user

  mount_uploader :media, MediaUploader
  mount_uploader :video, VideoUploader
  
  acts_as_votable
  
  acts_as_punchable
  
  def self.search(search)
  where("tweet_text LIKE ?", "%#{search}%")
  end
  
  def self.popularity(popularity)
  order("COALESCE(likes, ?) DESC").limit(5)
  end
  
  include SimpleHashtag::Hashtaggable
  hashtaggable_attribute :tweet_text
  
  include PublicActivity::Model
  tracked
  
end 
  
  

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessor :login

  self.per_page = 20

  extend FriendlyId
  friendly_id :username, use: [:slugged, :finders]

  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: { maximum: 100 }
  validates :username, presence: true, length: { maximum: 20 }, :uniqueness => { case_sensitive: false }

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships
  has_many :inverse_relationships, class_name: "Relationship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_relationships, source: :user
  has_many :favorites
  has_many :likes
  has_many :retweets, foreign_key: "retweeter_id"

  mount_uploader :avatar, AvatarUploader
  mount_uploader :cover, CoverUploader
  
  acts_as_messageable
  
  acts_as_liker
  
  is_impressionable
  
  acts_as_votable
  
  def mailboxer_email(object)
   #return the model's email here
  end


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
  
  def self.search(search)
  where("name LIKE ?", "%#{search}%")
  end 
  
  include PublicActivity::Model
  tracked
end

app/helpers/capsule_helper.rb
module CapsuleHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
  end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recap_helper.rb
module RecapHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def get_favorite(tweet_id)
    current_user.favorites.find_by(tweet_id: tweet_id)
  end

  def tweet_favored?(tweet_id)
    !get_favorite(tweet_id).nil?
  end

  def get_retweet(tweet_id)
    current_user.retweets.find_by(source_tweet_id: tweet_id)
  end

  def retweeted?(tweet_id)
    !get_retweet(tweet_id).nil?
  end

  def can_retweet?(tweet_id)
    Tweet.find(tweet_id).user != current_user
  end
  
   def get_like(tweet_id)
    current_user.likes.find_by(tweet_id: tweet_id)
   end

  def tweet_liked?(tweet_id)
    !get_like(tweet_id).nil?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def user_cover(user)
    if user.cover.url
      "background-image: url(#{ user.cover.url})"
    else
      "background: #ccc"
    end
  end

  def following?(user)
    !current_user.friends.find_by_id(user).nil?
  end

  def follows_you?(user)
    !user.friends.find_by_id(current_user).nil?
  end

  def relative_time(created_at)
    time_ago_in_words(created_at)
  end

  def formatted_time(created_at)
    created_at.strftime("%b %d, %Y")
  end

end

app/views/partials/_avatar.html.erb
<%= link_to user_path(user) do %>
  <%= image_tag user.avatar.url || 'avatar.jpg', class: klass %>
<% end %>

app/views/partials/_devise_form_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
  	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= resource.errors.full_messages.first %>
  </div>
<% end %>

app/views/partials/_error_message.html.erb
<% if error_message %>
  <div class="alert alert-dismissable alert-fixed alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <%= error_message %>
  </div>
<% end %>

app/views/partials/_follow.html.erb
<% if following?(user) %>
  <%= link_to fa_icon("check"), relationship_path(current_user.relationships.find_by_friend_id(user)), method: :delete, remote: true, class: 'btn btn-success' %>
<% else %>
  <%= link_to fa_icon("user-plus").html_safe, relationships_path(friend_id: user.id), method: :post, remote: true, class: 'btn btn-primary' %>
<% end %>

app/views/partials/_image_upload.html.erb
<div class="modal fade" id="image-upload-modal" tabindex="-1" role="dialog" aria-labelledby="imageUploadLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Media Upload</h4>
      </div>
      <div class="modal-body">
        <%= form_tag media_path, method: :post, class: "dropzone", id: "media-dropzone" do %>
          <div class="fallback">
            <%= file_field_tag :image, multiple: false %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/partials/_load_more.html.erb
<div id="loader", class="well text-center hidden">
  <%= image_tag "ajax-loader.gif" %>
  <%= will_paginate items %>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <!-- Brand and toggle get grouped for better mobile display -->
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <img class="navbar-brand" src="/prattsule2we.png">
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><a href="/index"><span class="glyphicon glyphicon-th-large" aria-hidden="true"></span></a></li>
        <li><a href="/explore"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a></li>
        <li><a href="/notifications"><span class="glyphicon glyphicon-cloud" aria-hidden="true"></span></a></li>
        <li><a href="/messages"><span class="glyphicon glyphicon-inbox" aria-hidden="true"></span></a></li>
      </ul>
      
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <form class= "navbar-form navbar-left" <%= form_tag search_results_path, method: 'get' do %> 
            <%= text_field_tag :search, params[:search], placeholder: "Search Prattsule", class: "form-control" %>
             <div class="form-group">
            </div>
          </form>
          <li>
            <a href="#", class="profile-image dropdown-toggle" data-toggle="dropdown", role="button", aria-expanded="false">
              <%= image_tag current_user.avatar, class: "avatar-xs" %>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "#{current_user.name}<br><b>@#{current_user.username}</b>".html_safe, user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to("Find Friends", find_friends_path) %></li>
              <li><%= link_to "Settings", user_path(current_user) %></li>
              <li><%= link_to('Sign out', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
          <form class="navbar-form navbar-right">
            <button id="new-tweet" type="button" data-toggle="modal" data-target="#new-tweet-modal" class="btn btn"><i class="fa fa-pencil"></i> Post</button>
          </form>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% end %>

app/views/partials/_new_tweet.html.erb
<%= form_tag tweets_path(parent_id: tweet_id), multipart: true, method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag "tweet[tweet_text]", nil, class: "form-control", placeholder: "Whats Happening?" %>
  </div>
  <div class="form-group hidden">
    <img id="tweet-img-preview">
    <a id="remove-tweet-img" href="#">&times;</a>
  </div>
  <div class="form-group">
    <%= hidden_field_tag "tweet[location]", nil %>
  </div>
  <div class="form-group">
    <%= file_field_tag "tweet[media]", class: "hidden", id: "media-upload-btn" %>
    <%= button_tag id: "tweet", class: "btn btn" do %>
      <%= fa_icon "pencil" %> Post
    <% end %>
    <div class="pull-right">
      <span id="tweet-count">140</span>
      <a id="ps-media-upload-btn" href="javascript:void(0);" class="btn btn-default">
        <i class="fa fa-camera"></i>
      </a>
      <a id="location-btn" href="#" class="btn btn-default">
        <i class="fa fa-map-marker"></i>
      </a>
    </div>
  </div>
<% end %>
<div id="tweet-error">
  <%= render 'partials/error_message', error_message: nil %>
</div>

app/views/partials/_reply_tweet.html.erb
   <div class="row">
  <div class="col-lg-10 col-lg-offset-1">
    <%= form_tag tweets_path(parent: tweet), method: :post, remote: true do %>
      <div class="form-group">
        <%= text_area_tag 'tweet[tweet_text]', "@#{tweet.user.username}", class: 'form-control', placeholder: 'Enter Reply' %>
      </div>
      <div class="form-group">
        <%= submit_tag 'Reply', id: 'tweet', class: 'btn btn-primary' %>
        <%= link_to 'Cancel', '#', class: 'btn btn-primary cancel-reply', onclick: 'removeParent(this);', "data-tweet": tweet.id %>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_tweet_modal.html.erb
<div class="modal fade" id="new-tweet-modal" tabindex="-1" role="dialog" aria-labelledby="new-tweet-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Compose New Post</h4>
      </div>
      <div class="modal-body">
        <%= render 'partials/new_tweet', tweet_id: nil %>
      </div>
    </div>
  </div>
</div>

app/views/partials/_user_info.html.erb
<div class="card">
  <div class="cover" data-cover="<%= user.cover %>">
    <%= image_tag user.avatar, class: "avatar" %>
  </div>
  <div class="about">
    <h3 class="name"><%= user.name %></h3>
    <h5 class="username"><b>@<%= user.username %></b></h5>
    <span class="content"><%= user.about %></span>
    <% if view_type == 'profile' %>
      <div class="row">
        <% unless @user.location.blank? %>
          <h5><i class="fa fa-map-marker"></i> <%= @user.location %></h5>
        <% end %>
        <% unless @user.website.blank? %>
          <h5><i class="fa fa-link"></i> <%= link_to @user.website, @user.website %></h5>
        <% end %>
        <h5><i class="fa fa-clock-o"></i> Joined <%= formatted_time(@user.created_at) %></h5>
      </div>
      <% else %>
      <div class="stats">
        <div class="row">
          <div class="col-lg-4 text-center">
            <%= link_to user_path(user) do %>
              <h5><b>Posts</b></h5>
              <h4 id="tweets-count"><%= user.tweets_count %></h4>
            <% end %>
          </div>
          <div class="col-lg-4 text-center">
            <%= link_to followers_user_path(user) do %>
              <h5><b>Followers</b></h5>
              <h4 id="followers-count"><%= user.followers_count %></h4>
            <% end %>
          </div>
          <div class="col-lg-4 text-center">
            <%= link_to following_user_path(user) do %>
              <h5><b>Following</b></h5>
              <h4 id="following-count"><%= user.following_count %></h4>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/partials/_video_upload.html.erb
<div class="modal fade" id="image-upload-modal" tabindex="-1" role="dialog" aria-labelledby="imageUploadLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Media Upload</h4>
      </div>
      <div class="modal-body">
        <%= form_tag media_path, method: :post, class: "dropzone", id: "media-dropzone" do %>
          <div class="fallback">
            <%= file_field_tag :video, multiple: false %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_activities.html.erb
<div class="col-sm-3">
  <ul class="list-group">
    <%= @activities.inspect %>
  </ul>
</div>
<div class="col-sm-3">
  <%= render_activities @activities %>
</div>